### ISSUE TITLE
Amazon Integration

### ISSUE THREAD

**Issue by bithack3r** [JonDerThan/annas-goodreads#9]
Hello mate, thank you for your work on the addon. Would it be possible for you to add the same feature with Amazon? 
`https://annas-archive.org/search?lang=&content=&ext=&sort=newest&q=`

**Comment by JonDerThan** [comment]
Thanks for the suggestion, but I don't really know how to implement this. Recognizing books on Goodreads is very easy (with CSS classes). On Amazon the books aren't very distinguished from other articles, so the add-on would have trouble deciding between normal articles and books. 

Also, I don't think that adding items to the right-click context menu is possible. And at this point, it may be more sensible to just add Anna's Archive as a search engine in Firefox: https://support.mozilla.org/en-US/kb/add-or-remove-search-engine-firefox.
